# Generated by Django 5.0.6 on 2024-07-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
