# Generated by Django 5.0.6 on 2024-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stock_alter_usermodel_email_alter_usermodel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
